// lib/teacher-data.ts

export type StudentData = {
  id: string
  name: string
  status: "offline" | "help"
  task: string
  progress: number
  lastSeen: string
  totalTime: number
  completedTasks: number
  avgScore: number
  className?: string
  currentTask?: string
  lastActivity?: string
  achievements?: number
  // Детальна статистика
  detailedStats?: {
    loginTime: string
    ip: string
    batteryLevel: number
    device: string
    offlineSessionsPercent: number
    completedTasksPercent: number
    avgTimeToSolution: number
    hintsRequested: number
    errorsCount: number
    aiRequestsCount: number
    sessions: {
      date: string
      duration: number
      tasksCompleted: number
      offline: boolean
    }[]
    taskHistory: {
      taskName: string
      completed: boolean
      timeSpent: number
      attempts: number
      hintsUsed: number
      date: string
    }[]
  }
}

export type ClassData = {
  id: string
  name: string
  profile: string
  totalStudents: number
  activeNow: number
  offlineHidden: number
  course: string
  avgScore: number
  avgProgress: number
  students: StudentData[]
  subject?: string
  practice?: string
  activeStudents?: number
}

export type TeacherDataType = {
  teacher: {
    name: string
    code: string
    practiceStart: string
    practiceEnd: string
  }
  classes: ClassData[]
}

export const TEACHER_DATA: TeacherDataType = {
  teacher: {
    name: "Турчин Д.О.",
    code: "Teacher443",
    practiceStart: "03.11.2025",
    practiceEnd: "21.11.2025",
  },

  classes: [
    {
      id: "10-a",
      name: "10-А",
      profile: "Math Profile",
      totalStudents: 30,
      activeNow: 0,
      offlineHidden: 0,
      course: "Адресація в Інтернеті та DNS",
      avgScore: 10.5,
      avgProgress: 67,
      students: [
        {
          id: "s1",
          name: "Шевченко О.",
          status: "offline",
          task: "Адресація IP - Маска підмережі",
          progress: 75,
          lastSeen: "21.11, 14:20",
          totalTime: 340,
          completedTasks: 23,
          avgScore: 11.2,
        },
        {
          id: "s2",
          name: "Бойко А.",
          status: "offline",
          task: "Адресація IP",
          progress: 45,
          lastSeen: "20.11, 15:30",
          totalTime: 280,
          completedTasks: 18,
          avgScore: 9.5,
        },
        {
          id: "s3",
          name: "Коваленко М.",
          status: "offline",
          task: "DNS Резолюція",
          progress: 60,
          lastSeen: "18.11, 11:45",
          totalTime: 310,
          completedTasks: 20,
          avgScore: 10.3,
        },
        {
          id: "s4",
          name: "Франко І.",
          status: "offline",
          task: "DHCP конфігурація",
          progress: 82,
          lastSeen: "21.11, 16:10",
          totalTime: 420,
          completedTasks: 26,
          avgScore: 11.8,
        },
        {
          id: "s5",
          name: "Петренко В.",
          status: "offline",
          task: "Маршрутизація",
          progress: 70,
          lastSeen: "21.11, 13:45",
          totalTime: 360,
          completedTasks: 22,
          avgScore: 10.7,
        },
        {
          id: "s6",
          name: "Мельник Т.",
          status: "offline",
          task: "NAT і PAT",
          progress: 55,
          lastSeen: "20.11, 12:20",
          totalTime: 290,
          completedTasks: 19,
          avgScore: 9.8,
        },
        {
          id: "s7",
          name: "Коваль С.",
          status: "offline",
          task: "Підмережі",
          progress: 88,
          lastSeen: "21.11, 15:30",
          totalTime: 450,
          completedTasks: 28,
          avgScore: 11.9,
        },
        {
          id: "s8",
          name: "Іваненко О.",
          status: "offline",
          task: "DNS records",
          progress: 42,
          lastSeen: "19.11, 14:10",
          totalTime: 260,
          completedTasks: 17,
          avgScore: 9.2,
        },
        {
          id: "s9",
          name: "Сидоренко К.",
          status: "offline",
          task: "IP адресація",
          progress: 65,
          lastSeen: "20.11, 16:40",
          totalTime: 330,
          completedTasks: 21,
          avgScore: 10.4,
        },
        {
          id: "s10",
          name: "Ткаченко М.",
          status: "offline",
          task: "Протоколи TCP/IP",
          progress: 78,
          lastSeen: "21.11, 14:55",
          totalTime: 390,
          completedTasks: 25,
          avgScore: 11.3,
        },
        {
          id: "s11",
          name: "Лисенко Н.",
          status: "offline",
          task: "Адресація IPv6",
          progress: 50,
          lastSeen: "20.11, 11:30",
          totalTime: 270,
          completedTasks: 18,
          avgScore: 9.6,
        },
        {
          id: "s12",
          name: "Гриценко В.",
          status: "offline",
          task: "Суbnetting",
          progress: 72,
          lastSeen: "21.11, 13:20",
          totalTime: 370,
          completedTasks: 23,
          avgScore: 10.9,
        },
        {
          id: "s13",
          name: "Павленко А.",
          status: "offline",
          task: "CIDR нотація",
          progress: 58,
          lastSeen: "19.11, 15:45",
          totalTime: 300,
          completedTasks: 19,
          avgScore: 10.1,
        },
        {
          id: "s14",
          name: "Кравченко О.",
          status: "offline",
          task: "Default Gateway",
          progress: 80,
          lastSeen: "21.11, 16:25",
          totalTime: 410,
          completedTasks: 26,
          avgScore: 11.5,
        },
        {
          id: "s15",
          name: "Романюк Д.",
          status: "offline",
          task: "DNS кеш",
          progress: 45,
          lastSeen: "20.11, 10:15",
          totalTime: 250,
          completedTasks: 17,
          avgScore: 9.3,
        },
        {
          id: "s16",
          name: "Білоус М.",
          status: "offline",
          task: "Маршрутизація",
          progress: 67,
          lastSeen: "21.11, 12:50",
          totalTime: 340,
          completedTasks: 21,
          avgScore: 10.5,
        },
        {
          id: "s17",
          name: "Данилюк І.",
          status: "offline",
          task: "ARP протокол",
          progress: 75,
          lastSeen: "20.11, 17:10",
          totalTime: 380,
          completedTasks: 24,
          avgScore: 11.1,
        },
        {
          id: "s18",
          name: "Зайцев С.",
          status: "offline",
          task: "Broadcast домен",
          progress: 52,
          lastSeen: "19.11, 13:25",
          totalTime: 285,
          completedTasks: 18,
          avgScore: 9.7,
        },
        {
          id: "s19",
          name: "Олійник Н.",
          status: "offline",
          task: "VLAN",
          progress: 85,
          lastSeen: "21.11, 15:40",
          totalTime: 430,
          completedTasks: 27,
          avgScore: 11.7,
        },
        {
          id: "s20",
          name: "Савченко В.",
          status: "offline",
          task: "IP forwarding",
          progress: 48,
          lastSeen: "20.11, 11:50",
          totalTime: 265,
          completedTasks: 17,
          avgScore: 9.4,
        },
        {
          id: "s21",
          name: "Гончар О.",
          status: "offline",
          task: "DNS зони",
          progress: 70,
          lastSeen: "21.11, 14:30",
          totalTime: 355,
          completedTasks: 22,
          avgScore: 10.8,
        },
        {
          id: "s22",
          name: "Литвин А.",
          status: "offline",
          task: "NAT таблиці",
          progress: 62,
          lastSeen: "20.11, 16:20",
          totalTime: 320,
          completedTasks: 20,
          avgScore: 10.2,
        },
        {
          id: "s23",
          name: "Чорний М.",
          status: "offline",
          task: "DHCP lease",
          progress: 55,
          lastSeen: "19.11, 12:40",
          totalTime: 290,
          completedTasks: 19,
          avgScore: 9.9,
        },
        {
          id: "s24",
          name: "Морозов Д.",
          status: "offline",
          task: "Маска підмережі",
          progress: 78,
          lastSeen: "21.11, 13:55",
          totalTime: 400,
          completedTasks: 25,
          avgScore: 11.2,
        },
        {
          id: "s25",
          name: "Ковальова К.",
          status: "offline",
          task: "DNS запити",
          progress: 43,
          lastSeen: "20.11, 10:45",
          totalTime: 255,
          completedTasks: 16,
          avgScore: 9.1,
        },
        {
          id: "s26",
          name: "Семенов В.",
          status: "offline",
          task: "IP класи",
          progress: 68,
          lastSeen: "21.11, 15:15",
          totalTime: 345,
          completedTasks: 21,
          avgScore: 10.6,
        },
        {
          id: "s27",
          name: "Василенко О.",
          status: "offline",
          task: "Суbnetting calc",
          progress: 73,
          lastSeen: "20.11, 14:35",
          totalTime: 375,
          completedTasks: 23,
          avgScore: 11.0,
        },
        {
          id: "s28",
          name: "Дмитрук Н.",
          status: "offline",
          task: "Gateway",
          progress: 50,
          lastSeen: "19.11, 16:10",
          totalTime: 275,
          completedTasks: 18,
          avgScore: 9.5,
        },
        {
          id: "s29",
          name: "Юрченко С.",
          status: "offline",
          task: "ICMP протокол",
          progress: 80,
          lastSeen: "21.11, 16:45",
          totalTime: 415,
          completedTasks: 26,
          avgScore: 11.4,
        },
        {
          id: "s30",
          name: "Гребенюк І.",
          status: "offline",
          task: "Routing table",
          progress: 58,
          lastSeen: "20.11, 13:20",
          totalTime: 305,
          completedTasks: 19,
          avgScore: 10.0,
        },
      ],
    },
    {
      id: "11-b",
      name: "11-Б",
      profile: "Standard",
      totalStudents: 28,
      activeNow: 0,
      offlineHidden: 0,
      course: "Flexbox практика",
      avgScore: 8.7,
      avgProgress: 54,
      students: [
        {
          id: "s31",
          name: "Мельник Т.",
          status: "offline",
          task: "Flexbox - Вирівнювання",
          progress: 68,
          lastSeen: "21.11, 13:30",
          totalTime: 310,
          completedTasks: 18,
          avgScore: 9.2,
        },
        {
          id: "s32",
          name: "Петренко В.",
          status: "offline",
          task: "Flexbox - Grid комбінація",
          progress: 72,
          lastSeen: "20.11, 17:45",
          totalTime: 340,
          completedTasks: 20,
          avgScore: 9.5,
        },
        {
          id: "s33",
          name: "Сидоренко К.",
          status: "offline",
          task: "Flexbox - Респонсив",
          progress: 55,
          lastSeen: "19.11, 12:20",
          totalTime: 280,
          completedTasks: 16,
          avgScore: 8.8,
        },
        {
          id: "s34",
          name: "Іваненко О.",
          status: "offline",
          task: "CSS Grid основи",
          progress: 40,
          lastSeen: "19.11, 10:15",
          totalTime: 240,
          completedTasks: 13,
          avgScore: 7.9,
        },
        {
          id: "s35",
          name: "Ткаченко М.",
          status: "offline",
          task: "Flexbox практика",
          progress: 85,
          lastSeen: "21.11, 15:50",
          totalTime: 390,
          completedTasks: 24,
          avgScore: 10.1,
        },
        {
          id: "s36",
          name: "Бондар А.",
          status: "offline",
          task: "Flex-wrap",
          progress: 62,
          lastSeen: "20.11, 14:25",
          totalTime: 295,
          completedTasks: 17,
          avgScore: 8.9,
        },
        {
          id: "s37",
          name: "Кузьменко Н.",
          status: "offline",
          task: "Align-items",
          progress: 50,
          lastSeen: "19.11, 16:30",
          totalTime: 265,
          completedTasks: 15,
          avgScore: 8.3,
        },
        {
          id: "s38",
          name: "Левченко С.",
          status: "offline",
          task: "Justify-content",
          progress: 75,
          lastSeen: "21.11, 14:40",
          totalTime: 350,
          completedTasks: 21,
          avgScore: 9.7,
        },
        {
          id: "s39",
          name: "Остапенко В.",
          status: "offline",
          task: "Flex-direction",
          progress: 48,
          lastSeen: "20.11, 11:40",
          totalTime: 255,
          completedTasks: 14,
          avgScore: 8.1,
        },
        {
          id: "s40",
          name: "Полтавець О.",
          status: "offline",
          task: "Flexbox layout",
          progress: 70,
          lastSeen: "21.11, 13:15",
          totalTime: 330,
          completedTasks: 19,
          avgScore: 9.3,
        },
        {
          id: "s41",
          name: "Романчук І.",
          status: "offline",
          task: "Flex-basis",
          progress: 45,
          lastSeen: "19.11, 15:20",
          totalTime: 245,
          completedTasks: 13,
          avgScore: 8.0,
        },
        {
          id: "s42",
          name: "Степаненко М.",
          status: "offline",
          task: "Flex-grow",
          progress: 65,
          lastSeen: "20.11, 16:50",
          totalTime: 315,
          completedTasks: 18,
          avgScore: 9.0,
        },
        {
          id: "s43",
          name: "Федоренко Н.",
          status: "offline",
          task: "Flex-shrink",
          progress: 52,
          lastSeen: "19.11, 13:45",
          totalTime: 270,
          completedTasks: 15,
          avgScore: 8.4,
        },
        {
          id: "s44",
          name: "Харченко В.",
          status: "offline",
          task: "Gap spacing",
          progress: 78,
          lastSeen: "21.11, 15:25",
          totalTime: 365,
          completedTasks: 22,
          avgScore: 9.8,
        },
        {
          id: "s45",
          name: "Шевчук А.",
          status: "offline",
          task: "Flex container",
          progress: 42,
          lastSeen: "20.11, 10:30",
          totalTime: 235,
          completedTasks: 12,
          avgScore: 7.8,
        },
        {
          id: "s46",
          name: "Ярема О.",
          status: "offline",
          task: "Flex items",
          progress: 68,
          lastSeen: "21.11, 14:10",
          totalTime: 325,
          completedTasks: 19,
          avgScore: 9.1,
        },
        {
          id: "s47",
          name: "Андрійчук С.",
          status: "offline",
          task: "Responsive flex",
          progress: 55,
          lastSeen: "20.11, 15:15",
          totalTime: 285,
          completedTasks: 16,
          avgScore: 8.6,
        },
        {
          id: "s48",
          name: "Бабенко М.",
          status: "offline",
          task: "Flexbox grid",
          progress: 73,
          lastSeen: "21.11, 16:30",
          totalTime: 355,
          completedTasks: 21,
          avgScore: 9.6,
        },
        {
          id: "s49",
          name: "Верещак Д.",
          status: "offline",
          task: "Media queries",
          progress: 38,
          lastSeen: "19.11, 11:50",
          totalTime: 225,
          completedTasks: 11,
          avgScore: 7.5,
        },
        {
          id: "s50",
          name: "Гаврилюк І.",
          status: "offline",
          task: "Flex order",
          progress: 60,
          lastSeen: "20.11, 13:40",
          totalTime: 300,
          completedTasks: 17,
          avgScore: 8.7,
        },
        {
          id: "s51",
          name: "Демченко Н.",
          status: "offline",
          task: "Nested flex",
          progress: 47,
          lastSeen: "19.11, 14:25",
          totalTime: 250,
          completedTasks: 14,
          avgScore: 8.2,
        },
        {
          id: "s52",
          name: "Жук В.",
          status: "offline",
          task: "Flex alignment",
          progress: 70,
          lastSeen: "21.11, 15:05",
          totalTime: 335,
          completedTasks: 20,
          avgScore: 9.4,
        },
        {
          id: "s53",
          name: "Кирилюк О.",
          status: "offline",
          task: "Auto margins",
          progress: 50,
          lastSeen: "20.11, 12:15",
          totalTime: 260,
          completedTasks: 15,
          avgScore: 8.3,
        },
        {
          id: "s54",
          name: "Лукашенко А.",
          status: "offline",
          task: "Flex практика",
          progress: 75,
          lastSeen: "21.11, 16:15",
          totalTime: 370,
          completedTasks: 22,
          avgScore: 9.9,
        },
        {
          id: "s55",
          name: "Мацюк С.",
          status: "offline",
          task: "Grid vs Flex",
          progress: 44,
          lastSeen: "19.11, 16:40",
          totalTime: 240,
          completedTasks: 13,
          avgScore: 7.9,
        },
        {
          id: "s56",
          name: "Нестеренко М.",
          status: "offline",
          task: "Flex centering",
          progress: 65,
          lastSeen: "20.11, 14:50",
          totalTime: 310,
          completedTasks: 18,
          avgScore: 8.9,
        },
        {
          id: "s57",
          name: "Онищенко В.",
          status: "offline",
          task: "Flex columns",
          progress: 53,
          lastSeen: "19.11, 13:10",
          totalTime: 275,
          completedTasks: 16,
          avgScore: 8.5,
        },
        {
          id: "s58",
          name: "Приходько І.",
          status: "offline",
          task: "Flexbox final",
          progress: 80,
          lastSeen: "21.11, 17:20",
          totalTime: 380,
          completedTasks: 23,
          avgScore: 10.0,
        },
      ],
    },
    {
      id: "7-a",
      name: "7-А",
      profile: "Алгоритми",
      totalStudents: 26,
      activeNow: 0,
      offlineHidden: 0,
      course: "Гра 'Робот' - Алгоритмічне мислення",
      avgScore: 9.8,
      avgProgress: 73,
      students: [
        {
          id: "s59",
          name: "Дмитренко А.",
          status: "offline",
          task: "Гра 'Робот' - Рівень 3",
          progress: 80,
          lastSeen: "21.11, 12:40",
          totalTime: 210,
          completedTasks: 12,
          avgScore: 10.5,
        },
        {
          id: "s60",
          name: "Ковальчук Н.",
          status: "offline",
          task: "Гра 'Робот' - Рівень 2",
          progress: 65,
          lastSeen: "20.11, 14:15",
          totalTime: 180,
          completedTasks: 10,
          avgScore: 9.8,
        },
        {
          id: "s61",
          name: "Романенко С.",
          status: "offline",
          task: "Гра 'Робот' - Рівень 4",
          progress: 50,
          lastSeen: "18.11, 16:30",
          totalTime: 160,
          completedTasks: 8,
          avgScore: 9.0,
        },
        {
          id: "s62",
          name: "Захарченко В.",
          status: "offline",
          task: "Гра 'Робот' - Рівень 3",
          progress: 75,
          lastSeen: "21.11, 13:25",
          totalTime: 195,
          completedTasks: 11,
          avgScore: 10.2,
        },
        {
          id: "s63",
          name: "Калашник О.",
          status: "offline",
          task: "Гра 'Робот' - Рівень 5",
          progress: 88,
          lastSeen: "21.11, 15:10",
          totalTime: 240,
          completedTasks: 14,
          avgScore: 11.0,
        },
        {
          id: "s64",
          name: "Міщенко І.",
          status: "offline",
          task: "Гра 'Робот' - Рівень 2",
          progress: 60,
          lastSeen: "20.11, 11:30",
          totalTime: 170,
          completedTasks: 9,
          avgScore: 9.5,
        },
        {
          id: "s65",
          name: "Новак М.",
          status: "offline",
          task: "Гра 'Робот' - Рівень 4",
          progress: 70,
          lastSeen: "21.11, 14:20",
          totalTime: 200,
          completedTasks: 11,
          avgScore: 10.0,
        },
        {
          id: "s66",
          name: "Оленко Н.",
          status: "offline",
          task: "Гра 'Робот' - Рівень 3",
          progress: 55,
          lastSeen: "19.11, 15:40",
          totalTime: 165,
          completedTasks: 9,
          avgScore: 9.2,
        },
        {
          id: "s67",
          name: "Павлюк С.",
          status: "offline",
          task: "Гра 'Робот' - Рівень 5",
          progress: 85,
          lastSeen: "21.11, 16:05",
          totalTime: 230,
          completedTasks: 13,
          avgScore: 10.8,
        },
        {
          id: "s68",
          name: "Руденко А.",
          status: "offline",
          task: "Гра 'Робот' - Рівень 2",
          progress: 48,
          lastSeen: "20.11, 10:50",
          totalTime: 155,
          completedTasks: 8,
          avgScore: 8.8,
        },
        {
          id: "s69",
          name: "Савчук В.",
          status: "offline",
          task: "Гра 'Робот' - Рівень 4",
          progress: 72,
          lastSeen: "21.11, 13:50",
          totalTime: 205,
          completedTasks: 12,
          avgScore: 10.1,
        },
        {
          id: "s70",
          name: "Тарасенко О.",
          status: "offline",
          task: "Гра 'Робот' - Рівень 3",
          progress: 62,
          lastSeen: "20.11, 15:20",
          totalTime: 175,
          completedTasks: 10,
          avgScore: 9.6,
        },
        {
          id: "s71",
          name: "Усенко М.",
          status: "offline",
          task: "Гра 'Робот' - Рівень 5",
          progress: 90,
          lastSeen: "21.11, 15:45",
          totalTime: 250,
          completedTasks: 15,
          avgScore: 11.2,
        },
        {
          id: "s72",
          name: "Фесенко Д.",
          status: "offline",
          task: "Гра 'Робот' - Рівень 2",
          progress: 52,
          lastSeen: "19.11, 12:15",
          totalTime: 160,
          completedTasks: 8,
          avgScore: 9.1,
        },
        {
          id: "s73",
          name: "Хоменко І.",
          status: "offline",
          task: "Гра 'Робот' - Рівень 4",
          progress: 68,
          lastSeen: "20.11, 16:35",
          totalTime: 190,
          completedTasks: 11,
          avgScore: 9.9,
        },
        {
          id: "s74",
          name: "Царенко Н.",
          status: "offline",
          task: "Гра 'Робот' - Рівень 3",
          progress: 58,
          lastSeen: "19.11, 14:50",
          totalTime: 168,
          completedTasks: 9,
          avgScore: 9.3,
        },
        {
          id: "s75",
          name: "Чумак С.",
          status: "offline",
          task: "Гра 'Робот' - Рівень 5",
          progress: 83,
          lastSeen: "21.11, 16:30",
          totalTime: 225,
          completedTasks: 13,
          avgScore: 10.6,
        },
        {
          id: "s76",
          name: "Шматко В.",
          status: "offline",
          task: "Гра 'Робот' - Рівень 2",
          progress: 45,
          lastSeen: "20.11, 11:05",
          totalTime: 150,
          completedTasks: 7,
          avgScore: 8.7,
        },
        {
          id: "s77",
          name: "Щербак О.",
          status: "offline",
          task: "Гра 'Робот' - Рівень 4",
          progress: 75,
          lastSeen: "21.11, 14:55",
          totalTime: 210,
          completedTasks: 12,
          avgScore: 10.3,
        },
        {
          id: "s78",
          name: "Яценко А.",
          status: "offline",
          task: "Гра 'Робот' - Рівень 3",
          progress: 60,
          lastSeen: "20.11, 13:10",
          totalTime: 172,
          completedTasks: 10,
          avgScore: 9.4,
        },
        {
          id: "s79",
          name: "Антоненко М.",
          status: "offline",
          task: "Гра 'Робот' - Рівень 5",
          progress: 87,
          lastSeen: "21.11, 17:15",
          totalTime: 235,
          completedTasks: 14,
          avgScore: 10.9,
        },
        {
          id: "s80",
          name: "Бережний Д.",
          status: "offline",
          task: "Гра 'Робот' - Рівень 2",
          progress: 50,
          lastSeen: "19.11, 15:25",
          totalTime: 158,
          completedTasks: 8,
          avgScore: 8.9,
        },
        {
          id: "s81",
          name: "Власенко І.",
          status: "offline",
          task: "Гра 'Робот' - Рівень 4",
          progress: 70,
          lastSeen: "20.11, 14:40",
          totalTime: 198,
          completedTasks: 11,
          avgScore: 9.8,
        },
        {
          id: "s82",
          name: "Горобець Н.",
          status: "offline",
          task: "Гра 'Робот' - Рівень 3",
          progress: 55,
          lastSeen: "19.11, 13:30",
          totalTime: 163,
          completedTasks: 9,
          avgScore: 9.2,
        },
        {
          id: "s83",
          name: "Довженко С.",
          status: "offline",
          task: "Гра 'Робот' - Рівень 5",
          progress: 92,
          lastSeen: "21.11, 17:00",
          totalTime: 255,
          completedTasks: 15,
          avgScore: 11.3,
        },
        {
          id: "s84",
          name: "Євтушенко В.",
          status: "offline",
          task: "Гра 'Робот' - Рівень 4",
          progress: 78,
          lastSeen: "21.11, 15:20",
          totalTime: 215,
          completedTasks: 12,
          avgScore: 10.4,
        },
      ],
    },
  ],

  // Real survey data statistics
  stats: {
    totalStudents: 84,
    activeStudents: 54, // Changed from 33 to 54
    surveyResponses: 33,
    practiceCompleted: true,
    offlineSessionsPercent: 76,
    completedTasksPercent: 88,
    avgTimeToSolve: 12, // minutes
    hintsRequestedPercent: 42,
    aiRequests: 142,
    aiEfficiency: 92,
  },

  // Activity by date (17-23 Dec with real peaks)
  activityData: [
    { date: "17.12", students: 38, sessions: 52 },
    { date: "18.12", students: 28, sessions: 41 },
    { date: "19.12", students: 31, sessions: 45 },
    { date: "20.12", students: 26, sessions: 38 },
    { date: "21.12", students: 22, sessions: 34 },
    { date: "22.12", students: 18, sessions: 27 },
    { date: "23.12", students: 41, sessions: 58 },
  ],

  // Survey comments
  surveyComments: [
    "Зручно, що можна працювати без інтернету!",
    "AI асистент дійсно допомагає, але не дає готові відповіді",
    "Інтерфейс простий та зрозумілий",
    "Хотілося б більше завдань з програмування",
    "Працює швидко навіть на старому телефоні",
  ],
}

export const teacherData = TEACHER_DATA
